### PR TITLE
Add Minecraft theme

### PR DESCRIPTION
**Pull request by Foxy-null**

### CODE REVIEW

**Comment by abdnh** [comment]
Nice theme! I'll merge this if @AnKingMed approves.

The sounds are quite big though (85 MB). Maybe long files can be cut or converted to ogg? The congrats sounds are especially long.

**Comment by Foxy-null** [comment]
Sure, I'm gonna change them to more simpler one!

**Comment by Foxy-null** [comment]
Thank you for the compliment! I'll go replace it with a shorter length audio file!

**Comment by AnKingMed** [comment]
yeah 85MB is a lot but if we're able to make it smaller then this looks great!

**Comment by Foxy-null** [comment]
Reduced the size of the entire "congrats" folder to only 126 KB!
Please take a look!

**Comment by Foxy-null** [comment]
Reduced the size of the entire "congrats" folder to only 126 KB!
Please take a look!
@abdnh @AnKingMed

**Comment by AnKingMed** [comment]
Sounds great! @abdnh as long as things are working this sounds awesome to me. @Foxy-null feel free to share on Reddit (or I can)

**Comment by Foxy-null** [comment]
I'm honored to hear that. I'm going to share on Reddit! Thank you so much!

**Pull request merged**
